apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: racks.airgap.example.com
spec:
  group: airgap.example.com
  scope: Cluster
  names:
    plural: racks
    singular: rack
    kind: Rack
    shortNames: ["rk"]
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Org
        type: string
        jsonPath: .spec.orgRef
      - name: Location
        type: string
        jsonPath: .spec.location
      - name: Servers
        type: integer
        jsonPath: .status.serverCount
      - name: Phase
        type: string
        jsonPath: .status.phase
      - name: Ready
        type: boolean
        jsonPath: .status.ready
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["orgRef", "location"]
              properties:
                orgRef:
                  type: string
                location:
                  type: string
                row:
                  type: string
                floor:
                  type: string
            status:
              type: object
              properties:
                ready:
                  type: boolean
                phase:
                  type: string
                observedGeneration:
                  type: integer
                serverCount:
                  type: integer
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
